# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/leo/cpu/vault.memo/v10.8ddr/v10.8ddr/v10.8ddr.cache/wt [current_project]
set_property parent.project_path /home/leo/cpu/vault.memo/v10.8ddr/v10.8ddr/v10.8ddr.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
add_files -quiet /home/leo/cpu/vault.memo/v10.8ddr/v10.8ddr/v10.8ddr.runs/axi_ethernetlite_0_synth_1/axi_ethernetlite_0.dcp
set_property used_in_implementation false [get_files /home/leo/cpu/vault.memo/v10.8ddr/v10.8ddr/v10.8ddr.runs/axi_ethernetlite_0_synth_1/axi_ethernetlite_0.dcp]
add_files -quiet /home/leo/cpu/vault.memo/v10.8ddr/v10.8ddr/v10.8ddr.runs/ddr_axi_synth_1/ddr_axi.dcp
set_property used_in_implementation false [get_files /home/leo/cpu/vault.memo/v10.8ddr/v10.8ddr/v10.8ddr.runs/ddr_axi_synth_1/ddr_axi.dcp]
add_files -quiet /home/leo/cpu/vault.memo/v10.8ddr/v10.8ddr/v10.8ddr.runs/axi_crossbar_0_synth_1/axi_crossbar_0.dcp
set_property used_in_implementation false [get_files /home/leo/cpu/vault.memo/v10.8ddr/v10.8ddr/v10.8ddr.runs/axi_crossbar_0_synth_1/axi_crossbar_0.dcp]
read_verilog -library xil_defaultlib {
  /home/leo/cpu/vault.memo/v10.8ddr/synthetic_op.v
  /home/leo/cpu/vault.memo/v10.8ddr/shiftbox.v
  /home/leo/cpu/vault.memo/v10.8ddr/arithbox.v
  /home/leo/cpu/vault.memo/v10.8ddr/udecox.v
  /home/leo/cpu/vault.memo/v10.8ddr/deco_rm.v
  /home/leo/cpu/vault.memo/v10.8ddr/deco8.v
  /home/leo/cpu/vault.memo/v10.8ddr/vliw.v
  /home/leo/cpu/vault.memo/v10.8ddr/deco.v
  /home/leo/cpu/vault.memo/v10.8ddr/cmp14.v
  /home/leo/cpu/vault.memo/v10.8ddr/cacheram.v
  /home/leo/cpu/vault.memo/v10.8ddr/acu.v
  /home/leo/cpu/vault.memo/v10.8ddr/useq_cache_8k_ddr.v
  /home/leo/cpu/vault.memo/v10.8ddr/Itlb.v
  /home/leo/cpu/vault.memo/v10.8ddr/Dtlb.v
  /home/leo/cpu/vault.memo/v10.8ddr/datacache.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_inv.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_mux4.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_ao3.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_ao4.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_or4.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_ha2.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_or2.v
  /home/leo/cpu/vault.memo/v10.8ddr/v8253_counter.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_xor2.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_reg.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_reg_set.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_nao4.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_nao3.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_and2.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_nor4.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_nand2.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_and3.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_nand3.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_nor2.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_and4.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_mux2.v
  /home/leo/cpu/vault.memo/v10.8ddr/notech/notech_fa2.v
  /home/leo/cpu/vault.memo/v10.8ddr/cpu.v
  /home/leo/cpu/vault.memo/v10.8ddr/biu32_axi.v
  /home/leo/cpu/vault.memo/v10.8ddr/tiny_spi.v
  /home/leo/cpu/vault.memo/v10.8ddr/v8253.v
  /home/leo/cpu/vault.memo/v10.8ddr/uart_16750.v
  /home/leo/cpu/vault.memo/v10.8ddr/v8259.v
  /home/leo/cpu/vault.memo/v10.8ddr/v8042_stub.v
  /home/leo/cpu/vault.memo/v10.8ddr/core.v
  /home/leo/cpu/vault.memo/v10.8ddr/clk_wiz_0.v
  /home/leo/cpu/vault.memo/v10.8ddr/v586.v
  /home/leo/cpu/vault.memo/v10.8ddr/axi_rom.v
  /home/leo/cpu/vault.memo/v10.8ddr/periph.v
  /home/leo/cpu/vault.memo/v10.8ddr/rstgen.V
  /home/leo/cpu/vault.memo/v10.8ddr/TOP_SYS.v
}
read_xdc /home/leo/cpu/vault.memo/v10.8ddr/TOP_SYS.xdc
set_property used_in_implementation false [get_files /home/leo/cpu/vault.memo/v10.8ddr/TOP_SYS.xdc]

synth_design -top TOP_SYS -part xc7a100tcsg324-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5
write_checkpoint -noxdef TOP_SYS.dcp
catch { report_utilization -file TOP_SYS_utilization_synth.rpt -pb TOP_SYS_utilization_synth.pb }
