# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/leo/cpu/svn4/trunk/xci/mii_to_rmii/mii_to_rmii_0.xci
# IP: The module: 'mii_to_rmii_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/leo/cpu/svn4/trunk/xci/mii_to_rmii/mii_to_rmii_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mii_to_rmii_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/leo/cpu/svn4/trunk/xci/mii_to_rmii/mii_to_rmii_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mii_to_rmii_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/leo/cpu/svn4/trunk/xci/mii_to_rmii/mii_to_rmii_0.xci
# IP: The module: 'mii_to_rmii_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/leo/cpu/svn4/trunk/xci/mii_to_rmii/mii_to_rmii_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mii_to_rmii_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/leo/cpu/svn4/trunk/xci/mii_to_rmii/mii_to_rmii_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mii_to_rmii_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
