# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/leo/cpu/vault.memo/v10.8ddr/v10.8ddr/v10.8ddr.cache/wt [current_project]
set_property parent.project_path /home/leo/cpu/vault.memo/v10.8ddr/v10.8ddr/v10.8ddr.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
read_ip /home/leo/cpu/vault.memo/v10.8ddr/v10.8ddr/v10.8ddr.srcs/sources_1/ip/ddr_axi/ddr_axi.xci
set_property used_in_implementation false [get_files -all /home/leo/cpu/vault.memo/v10.8ddr/v10.8ddr/v10.8ddr.srcs/sources_1/ip/ddr_axi/ddr_axi.dcp]
set_property is_locked true [get_files /home/leo/cpu/vault.memo/v10.8ddr/v10.8ddr/v10.8ddr.srcs/sources_1/ip/ddr_axi/ddr_axi.xci]

synth_design -top ddr_axi -part xc7a100tcsg324-1 -directive AreaOptimizedHigh -resource_sharing on -control_set_opt_threshold 1 -mode out_of_context
rename_ref -prefix_all ddr_axi_
write_checkpoint -noxdef ddr_axi.dcp
catch { report_utilization -file ddr_axi_utilization_synth.rpt -pb ddr_axi_utilization_synth.pb }
if { [catch {
  file copy -force /home/leo/cpu/vault.memo/v10.8ddr/v10.8ddr/v10.8ddr.runs/ddr_axi_synth_1/ddr_axi.dcp /home/leo/cpu/vault.memo/v10.8ddr/v10.8ddr/v10.8ddr.srcs/sources_1/ip/ddr_axi/ddr_axi.dcp
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /home/leo/cpu/vault.memo/v10.8ddr/v10.8ddr/v10.8ddr.srcs/sources_1/ip/ddr_axi/ddr_axi_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /home/leo/cpu/vault.memo/v10.8ddr/v10.8ddr/v10.8ddr.srcs/sources_1/ip/ddr_axi/ddr_axi_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /home/leo/cpu/vault.memo/v10.8ddr/v10.8ddr/v10.8ddr.srcs/sources_1/ip/ddr_axi/ddr_axi_funcsim.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /home/leo/cpu/vault.memo/v10.8ddr/v10.8ddr/v10.8ddr.srcs/sources_1/ip/ddr_axi/ddr_axi_funcsim.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
